version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: priorisen-backend
    container_name: priorisen_backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/var/www

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: priorisen-frontend
    container_name: priorisen_frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    command: npm run dev
