services:
    - type: web
      name: prioreisen-api
      runtime: docker
      plan: free
      region: frankfurt
      envVars:
          - key: APP_NAME
            value: Prioreisen
          - key: APP_ENV
            value: production
          - key: APP_KEY
            generateValue: true
          - key: APP_DEBUG
            value: false
          - key: APP_URL
            sync: false
          - key: LOG_CHANNEL
            value: stack
          - key: LOG_LEVEL
            value: error
          - key: DB_CONNECTION
            value: pgsql
          - key: DB_HOST
            fromDatabase:
                name: prioreisen-db
                property: host
          - key: DB_PORT
            fromDatabase:
                name: prioreisen-db
                property: port
          - key: DB_DATABASE
            fromDatabase:
                name: prioreisen-db
                property: database
          - key: DB_USERNAME
            fromDatabase:
                name: prioreisen-db
                property: user
          - key: DB_PASSWORD
            fromDatabase:
                name: prioreisen-db
                property: password
          - key: SESSION_DRIVER
            value: cookie
          - key: QUEUE_CONNECTION
            value: sync
          - key: CACHE_DRIVER
            value: file

databases:
    - name: prioreisen-db
      databaseName: prioreisen
      plan: free
      region: frankfurt
